"""The desktop this process drives: one platform adapter, chosen once, behind one name.

Every other module reaches the platform through `desktop` and never imports macos.py or windows.py
itself. Windows gets windows.py. Every other OS gets macos.py, the default: on macOS it is the real
adapter, and on the Linux test runner tests/conftest.py stands in for the modules it imports, so the
suite runs there unchanged. Only the Windows path imports a Windows-only package.

`Desktop` is the surface both adapters provide, and tests/test_platform_adapter.py holds each of
them to it, parameter for parameter.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Protocol

from PIL import Image

from .models import AxNode, Box, Field, MenuItem, WindowRef

OcrLine = tuple[str, float, Box]  # text, confidence, box in the image's own pixels


class Desktop(Protocol):
    # the escape hatch
    def check_abort(self) -> None: ...
    def sleep_watching(self, seconds: float) -> None: ...
    def accessibility_trusted(self) -> bool: ...

    # input
    def click_at(self, point: tuple[float, float], clicks: int = 1, right: bool = False) -> None: ...
    def press(self, key: str, command: bool = False, shift: bool = False) -> None: ...
    def type_text(self, text: str) -> None: ...
    def clear_field(self) -> None: ...
    def scroll(self, lines: int) -> None: ...

    # apps and windows
    def frontmost_app_and_pid(self) -> tuple[str, int]: ...
    def activate(self, app: str, timeout: float = 3.0) -> bool: ...
    def open_url(self, browser: str, url: str) -> bool: ...
    def browser_url(self, browser: str) -> str | None: ...
    def open_path(self, path: Path, as_text: bool = False) -> None: ...
    def frontmost_window_bounds(self, pid: int | None = None) -> tuple[float, float, float, float] | None: ...
    def installed_apps(self) -> list[str]: ...
    def running_apps(self) -> set[str]: ...
    def app_windows(self, pid: int, limit: int = 12) -> list[WindowRef]: ...
    def raise_window(self, ref) -> bool: ...
    def menu_items(self, pid: int, limit: int) -> list[MenuItem]: ...
    def clipboard_text(self) -> str: ...

    # capture, OCR, and accessibility
    def active_displays(self) -> list[tuple[float, float, float, float]]: ...
    def screenshot(self, display: int = 1) -> Image.Image: ...
    def display_scale(self, image: Image.Image, bounds: tuple[float, float, float, float] | None = None) -> float: ...
    def recognize_text(self, image: Image.Image) -> list[OcrLine]: ...
    def focused_field(self) -> Field | None: ...
    def actionable_elements(
        self, pid: int, display_w_pt: float, display_h_pt: float
    ) -> tuple[list[AxNode], list[AxNode], bool]: ...
    def nameless_elements(self, pid: int, display_w_pt: float, display_h_pt: float) -> list[AxNode]: ...

    # acting on an element
    def ax_press(self, ref) -> bool: ...
    def ax_focus(self, ref) -> bool: ...
    def ax_set_value(self, ref, text: str) -> bool: ...
    def ax_value(self, ref) -> str | None: ...


if sys.platform == "win32":
    from . import windows as _adapter
else:
    from . import macos as _adapter

desktop: Desktop = _adapter
